<script></script>
<template>
    <!--HTML-->
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    </head>
    <body>
        <header>
            <h1>EcoWave</h1>
        </header>
    <main></main>
    <footer></footer> 
</body>
</template>
<style>
    /*CSS*/
    *{
        font-family: "Inter";
        margin: 0;
    }
    header{
        background-color: #3DA92C;
        color: white;
        justify-content: center;
        text-align: center;
        padding-top: 15px;
        padding-bottom:15px ;
    }
    footer {
    background-color: #3DA92C;
    padding: 30px;
    }
</style>

